name: bow_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  archive: ^4.0.9
  file_selector: ^1.1.0
  # permission_handler: ^11.3.0
  flutter:
    sdk: flutter
  speech_to_text: ^7.3.0
  syncfusion_flutter_pdf: ^33.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  iconly: ^1.0.1
  http: ^1.6.0
  shared_preferences: ^2.2.2
  share_plus: ^13.0.0
  flutter_dotenv: ^6.0.0
  clipboard: ^3.0.14
  google_fonts: ^8.0.2
  flutter_markdown: ^0.6.10
  markdown: ^7.3.1

flutter:
  uses-material-design: true
